name: Docker Images

on:
  push:
    paths:
      # Build on changes to any files included in the image.
      - Dockerfile
      - lint.php

jobs:
  bake:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
      
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/bake-action@v5
        if: github.ref_name != 'main'
      
      - name: Build and push
        uses: docker/bake-action@v5
        if: github.ref_name == 'main'
        with:
          set: '*.platform=linux/amd64,linux/arm64'
          push: true